/**
 * Password login (sessions) + user-generated API tokens.
 *
 * Replaces the old static LIFEOS_TOKEN env var entirely. Two credential types now:
 *   - Session cookie: browser logs in with username+password, gets an httpOnly cookie.
 *     No expiry by design — a session is valid until an explicit /auth/logout deletes
 *     its row. (Same "no TTL" property the old shared token always had; naming it
 *     explicitly here rather than leaving it implicit.)
 *   - API token: generated by the user, post-login, in Settings -> Security. For MCP
 *     clients, scripts, curl. Shown once at creation; only its SHA-256 hash is stored.
 */
import type { Context } from "hono";
import { getCookie, setCookie, deleteCookie } from "hono/cookie";
import { q, q1, run } from "./db.ts";

export const SESSION_COOKIE = "lifeos_session";

// ── crypto helpers ───────────────────────────────────────────────────────────
// Password hashing: Bun's native argon2id. No dependency needed.
export const hashPassword = (pw: string) => Bun.password.hash(pw);
export const verifyPassword = (pw: string, hash: string) => Bun.password.verify(pw, hash);

// Session/API tokens are already high-entropy random (not human-chosen), so a fast
// cryptographic hash is the right tool here, not the deliberately-slow argon2id above.
export async function sha256Hex(input: string): Promise<string> {
  const buf = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(input));
  return Array.from(new Uint8Array(buf)).map(b => b.toString(16).padStart(2, "0")).join("");
}

// 32 random bytes -> 64 hex chars. Same format/entropy as the old `openssl rand -hex 32`
// convention for LIFEOS_TOKEN, so anything that logged/compared token length elsewhere
// keeps working unchanged.
export function randomHex(bytes = 32): string {
  const arr = new Uint8Array(bytes);
  crypto.getRandomValues(arr);
  return Array.from(arr).map(b => b.toString(16).padStart(2, "0")).join("");
}

// ── cookie security ──────────────────────────────────────────────────────────
// `Secure` must be conditional: hardcoding it would break plain-HTTP LAN access
// (http://neo.local:3000) since browsers refuse to send Secure cookies over HTTP.
// Cloudflare Tunnel sets X-Forwarded-Proto: https on the way in, so we detect that;
// LAN/local requests won't have it and get a non-Secure cookie, which is correct.
function isHttpsRequest(c: Context): boolean {
  return c.req.header("x-forwarded-proto") === "https";
}

// ── sessions (password login) ────────────────────────────────────────────────
export async function createSession(c: Context): Promise<void> {
  const token = randomHex();
  const hash = await sha256Hex(token);
  const now = new Date().toISOString();
  run("INSERT INTO sessions(token_hash,created_at,last_seen_at) VALUES(?,?,?)", hash, now, now);
  setCookie(c, SESSION_COOKIE, token, {
    httpOnly: true,
    sameSite: "Lax",
    secure: isHttpsRequest(c),
    path: "/",
    // No maxAge/expires: a session cookie in the browser sense, but since the
    // underlying `sessions` row also never expires, closing the browser and
    // reopening it still finds a valid session (this is what "persist until
    // logged out" means in practice for a cookie with no Max-Age).
  });
}

export async function destroySession(c: Context): Promise<void> {
  const token = getCookie(c, SESSION_COOKIE);
  if (token) {
    const hash = await sha256Hex(token);
    run("DELETE FROM sessions WHERE token_hash=?", hash);
  }
  deleteCookie(c, SESSION_COOKIE, { path: "/" });
}

async function checkSession(c: Context): Promise<boolean> {
  const token = getCookie(c, SESSION_COOKIE);
  if (!token) return false;
  const hash = await sha256Hex(token);
  const row = q1<{ token_hash: string }>("SELECT token_hash FROM sessions WHERE token_hash=?", hash);
  if (!row) return false;
  run("UPDATE sessions SET last_seen_at=? WHERE token_hash=?", new Date().toISOString(), hash);
  return true;
}

// ── API tokens (MCP / scripts / curl) ────────────────────────────────────────
export async function createApiToken(name: string): Promise<string> {
  const token = randomHex();
  const hash = await sha256Hex(token);
  run("INSERT INTO api_tokens(name,token_hash,created_at) VALUES(?,?,?)", name.trim() || "Unnamed token", hash, new Date().toISOString());
  return token; // raw value — caller must show this to the user NOW, it's never retrievable again
}

async function checkApiToken(raw: string): Promise<boolean> {
  const hash = await sha256Hex(raw);
  const row = q1<{ id: number }>("SELECT id FROM api_tokens WHERE token_hash=?", hash);
  if (!row) return false;
  run("UPDATE api_tokens SET last_used_at=? WHERE id=?", new Date().toISOString(), row.id);
  return true;
}

// ── combined request auth check ──────────────────────────────────────────────
// Returns which method authenticated the request, or null if neither did. Route
// handlers that manage API tokens (create/list/revoke) require "session" specifically
// — a leaked API token must never be usable to mint or enumerate more tokens.
export async function authenticate(c: Context): Promise<"session" | "api_token" | null> {
  if (await checkSession(c)) return "session";
  const auth = c.req.header("Authorization") ?? "";
  const bearer = auth.startsWith("Bearer ") ? auth.slice(7) : (c.req.query("token") ?? null);
  if (bearer && await checkApiToken(bearer)) return "api_token";
  return null;
}

// ── login rate limiting ───────────────────────────────────────────────────────
// ponytail: simple fixed-window counter (last 15 min, per-process, no per-IP split) —
// enough to stop a naive brute-force script against a single-user instance. Upgrade
// to per-IP + exponential backoff if this is ever multi-tenant.
const WINDOW_MS = 15 * 60_000;
const MAX_ATTEMPTS = 10;

export function isLoginRateLimited(): boolean {
  const since = new Date(Date.now() - WINDOW_MS).toISOString();
  const row = q1<{ n: number }>("SELECT COUNT(*) n FROM login_attempts WHERE attempted_at>=? AND success=0", since);
  return (row?.n ?? 0) >= MAX_ATTEMPTS;
}

export function recordLoginAttempt(success: boolean): void {
  run("INSERT INTO login_attempts(attempted_at,success) VALUES(?,?)", new Date().toISOString(), success ? 1 : 0);
  // Housekeeping: don't let this table grow forever. Trim anything older than the window.
  const since = new Date(Date.now() - WINDOW_MS).toISOString();
  run("DELETE FROM login_attempts WHERE attempted_at<?", since);
}
